### ISSUE TITLE
class_dict.csv

### ISSUE THREAD

**Issue by marknabil** [rechardchen123/ASV_Image_Segmentation#1]
Where can this csv be found ? or how to generate it from  MaSTr1325 dataset ? 
Thanks

**Comment by rechardchen123** [comment]
Thank you for raising this issue. I have indicated that the `class_dict.csv` is a colour value table in the `readme` of the third outline `03. transfer the image annotations into RGB format`. You can build a file named `class_dict.csv` by yourself under your dataset file like this table. 
![2021-11-16_191840](https://user-images.githubusercontent.com/11623615/142051090-1fa5b9c6-b9c8-4a39-9c2a-bf1c77110dbf.jpg)
If you have any problems, please feel free to contact me.

**Comment by marknabil** [comment]
Thanks a lot I thought it is per test image, but now I understand it is a mask color mapping.
